version: "3.9"

services:
  bot:
    build: .
    container_name: bot-maracana
    restart: always
    env_file:
      - .env
    environment:
      SQLITE_DB_PATH: /app/data/usuarios.db
    volumes:
      - ./data:/app/data